### ISSUE TITLE
How do you open the window?

### ISSUE THREAD

**Issue by matthew-dean** [nertilpoci/VisualStudio-Filterable-Output-Window-Extensions#22]
Unfortunately, Visual Studio is not great with surfacing settings for extensions. I have the Output Filter extension installed. How do I find the new window for the output filter? I can't find it under any menu.

**Comment by LuckyBrain** [comment]
@matthew-dean: I'm a user and I could find it under **View** > **Other Windows** > **Output Filter**.  I hope that helps!
